[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_current = "5xcosctyu88U7nAcRniYisw96kppr3KNZxqYMogRrE2j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"

